import { Course } from '@/lib/types/courseType';

// export const dummyCourses: Course[] = [
//   {
//     id: 1,
//     title: 'ENGINEERING PHYSICS-1 (FULL SYLLABUS + PYQS)',
//     image: '/images/engineering_physics.jpg',
//     target: '1st Year Students',
//     startDate: '27th July, 2025',
//     endDate: '31st March, 2026',
//     price: 499,
//     originalPrice: 999,
//     discountLabel: 50,
//     description: 'Complete coverage of Engineering Physics-1 with PYQs.',
//     educator: [
//         {
//             name: 'Sayantan Guha',
//             image: '/images/Sayantan Sir.png',
//             subject: 'Engineering Physics-1',
//         },
//     ],
//     educator_id: 101,
//     created_at: '2025-06-01T10:00:00Z',
//     updated_at: '2025-06-05T10:00:00Z',
//     demoVideos: [
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//     ],
//   },
//   {
//     id: 2,
//     title: 'ENGINEERING CHEMISTRY-1 (FULL SYLLABUS + PYQS)',
//     image: '/images/engineering_chemistry.jpg',
//     target: '1st Year Students',
//     startDate: '27th July, 2025',
//     endDate: '31st March, 2026',
//     price: 499,
//     originalPrice: 999,
//     discountLabel: 50,
//     description: 'Comprehensive course for Engineering Chemistry-1 including PYQs.',
//     educator: [
//         {
//             name: 'Sougata Patra',
//             image: '/images/Sougata.png',
//             subject: 'Engineering Chemistry-1',
//         },
//     ],
//     educator_id: 102,
//     created_at: '2025-06-02T10:00:00Z',
//     updated_at: '2025-06-06T10:00:00Z',
//     demoVideos: [
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//     ],
//   },
//   {
//     id: 3,
//     title: 'BASIC ELECTRICAL ENGINEERING (FULL SYLLABUS + PYQS)',
//     image: '/images/basic_electrical_engineering.jpg',
//     target: '1st Year Students',
//     startDate: '27th July, 2025',
//     endDate: '31st March, 2026',
//     price: 499,
//     originalPrice: 999,
//     discountLabel: 50,
//     description: 'Covers full syllabus and previous questions in BEE.',
//     educator: [
//         {
//             name: 'Ashish Kumar',
//             image: '/images/Ashish.png',
//             subject: 'Basic Electrical Engineering',
//         }
//     ],
//     educator_id: 103,
//     created_at: '2025-06-03T10:00:00Z',
//     updated_at: '2025-06-07T10:00:00Z',
//     demoVideos: [
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//     ],
//   },
//   {
//     id: 4,
//     title: 'C PROGRAMMING (FULL CONCEPT + CODES)',
//     image: '/images/c_programming.jpg',
//     target: '1st Year Students',
//     startDate: '27th July, 2025',
//     endDate: '31st March, 2026',
//     price: 499,
//     originalPrice: 999,
//     discountLabel: 50,
//     description: 'Concept-based learning with real coding practice in C.',
//     educator: [
//         {
//             name: 'Molla Akifur Rahman',
//             image: '/images/Akifur.png',
//             subject: 'C Programming',
//         },
//     ],
//     educator_id: 104,
//     created_at: '2025-06-04T10:00:00Z',
//     updated_at: '2025-06-08T10:00:00Z',
//     demoVideos: [
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//     ],
//   },
//   {
//     id: 5,
//     title: 'MATHEMATICS-1B (BSM102)',
//     image: '/images/mathematics_1B.jpg',
//     target: '1st Year Students',
//     startDate: '27th July, 2025',
//     endDate: '31st March, 2026',
//     price: 199,
//     originalPrice: 349,
//     discountLabel: 50,
//     description: 'All topics of BSM102 covered with solved examples.',
//     educator: [
//         {
//         name: 'Srijan Dutta',
//         image: '/images/Srijan.png',
//         subject: 'Mathematics-1B (BSM102)',
//         },
//     ],     
//     educator_id: 105,
//     created_at: '2025-06-05T10:00:00Z',
//     updated_at: '2025-06-09T10:00:00Z',
//     demoVideos: [
//       'https://www.youtube.com/watch?v=1tf2uKbM4rA&list=PLn3Wz38keZOfEEJmNHNBlnHoepR8wv8gU&index=2',
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//     ],
//   },
//   {
//     id: 6,
//     title: 'MATHEMATICS-1A (BSM101)',
//     image: '/images/mathematics-1A.jpg',
//     target: '1st Year Students',
//     startDate: '27th July, 2025',
//     endDate: '31st March, 2026',
//     price: 199,
//     originalPrice: 349,
//     discountLabel: 50,
//     description: 'Thorough explanation of all BSM101 concepts.',
//     educator: [
//         {
//       name: 'Srijan Dutta',
//       image: '/images/Srijan.png',
//       subject: 'Mathematics-1A (BSM101)',
//         },
//     ],
//     educator_id: 105,
//     created_at: '2025-06-06T10:00:00Z',
//     updated_at: '2025-06-10T10:00:00Z',
//     demoVideos: [
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//     ],
//   },
//   {
//     id: 7,
//     title: 'BUMPER OFFER (COMBO 1)',
//     image: '/images/bumperoffer1.jpg',
//     target: '1st Year Students',
//     startDate: '27th July, 2025',
//     endDate: '31st March, 2026',
//     price: 999,
//     originalPrice: 2199,
//     discountLabel: 50,
//     description: 'Combo course covering multiple subjects by top educators.',
//     educator_id: 999,
//     created_at: '2025-06-07T10:00:00Z',
//     updated_at: '2025-06-11T10:00:00Z',
//     demoVideos: [
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//     ],
//     educator: [
//       {
//         name: 'Srijan Dutta',
//         subject: 'Mathematics-1B (BSM102)',
//         image: '/images/Srijan.png',
//       },
//       {
//         name: 'Sougata Patra',
//         subject: 'Engineering Chemistry-1',
//         image: '/images/Sougata.png',
//       },
//       {
//         name: 'Ashish Kumar',
//         subject: 'Basic Electrical Engineering',
//         image: '/images/Ashish.png',
//       },
//     ],
//   },
//   {
//     id: 8,
//     title: 'BUMPER OFFER (COMBO 2)',
//     image: '/images/bumper_offer2.jpg',
//     target: '1st Year Students',
//     startDate: '27th July, 2025',
//     endDate: '31st March, 2026',
//     price: 999,
//     originalPrice: 2199,
//     discountLabel: 50,
//     description: 'Bundle covering Engg Physics, Math, and BEE.',
//     educator_id: 998,
//     created_at: '2025-06-08T10:00:00Z',
//     updated_at: '2025-06-12T10:00:00Z',
//     demoVideos: [
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//       'https://www.youtube.com/watch?v=Z2N5a7XZWg8',
//     ],
//     educator: [
//       {
//         name: 'Srijan Dutta',
//         subject: 'Mathematics-1A (BSM101)',
//         image: '/images/Srijan.png',
//       },
//       {
//         name: 'Sayantan Guha',
//         subject: 'Engineering Physics-1',
//         image: '/images/Sayantan Sir.png',
//       },
//       {
//         name: 'Ashish Kumar',
//         subject: 'Basic Electrical Engineering',
//         image: '/images/Ashish.png',
//       },
//     ],
//   },
// ];
