import React from "react";
import Footer from "@/components/LandingComponents/Footer";

const PrivacyPolicyPage = () => {
  return (
    <div>
      <div className="max-w-5xl mx-auto px-6 py-12">
        <h1 className="text-4xl text-[rgb(108,76,241)] font-bold text-center mb-4">
          Privacy Policy
        </h1>

        <p className="text-black text-lg mb-2">
          <strong>Last Updated: 23 July 2025</strong>
        </p>

        <section className="space-y-6 text-black text-lg">
          <p>
            This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use our Service, and informs you about your privacy rights and how the law protects you.
          </p>
          <p>
            We use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold mt-6">1. Interpretation and Definitions</h2>
          <h3 className="text-xl text-[rgb(108,76,241)] font-medium mt-4">Interpretation</h3>
          <p>
            Words with capitalized initials have meanings defined under the conditions below. The same definitions apply whether they appear in singular or plural.
          </p>

          <h3 className="text-xl text-[rgb(108,76,241)] font-medium mt-4">Definitions</h3>
          <ul className="list-disc ml-6 space-y-2">
            <li><strong>Account</strong> means a unique account created for you to access our Service.</li>
            <li><strong>Affiliate</strong> means any entity that controls, is controlled by, or is under common control with a party.</li>
            <li><strong>Application</strong> refers to Knowledge Gate, the software program provided by the Company.</li>
            <li><strong>Company</strong> (referred to as “we”, “us”, or “our”) refers to Tending To Infinity.</li>
            <li><strong>Cookies</strong> are small files placed on your device by a website to store data such as browsing history.</li>
            <li><strong>Country</strong> refers to: West Bengal, India.</li>
            <li><strong>Device</strong> means any device that can access the Service, such as a computer, mobile phone, or tablet.</li>
            <li><strong>Personal Data</strong> means any information relating to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Application, Website, or both.</li>
            <li><strong>Service Provider</strong> refers to any third-party company or individual employed by us to facilitate or provide the Service, or to analyze usage.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the infrastructure itself.</li>
            <li><strong>Website</strong> refers to <i>Tending To Infinity</i>, accessible at <a className="text-blue-500" target="blank" href="https://tendingtoinfinityacademy.com/">https://tendingtoinfinityacademy.com/</a>.</li>
            <li><strong>You</strong> refers to the individual accessing or using the Service.</li>
          </ul>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold mt-6">2. Types of Data Collected</h2>
          <h3 className="text-xl font-medium text-[rgb(108,76,241)]">Personal Data</h3>
          <p>We may collect personally identifiable information such as:</p>
          <ul className="list-disc ml-6 space-y-2">
            <li>Full name</li>
            <li>Email address</li>
            <li>Phone number</li>
            <li>Profile photo</li>
            <li>Address (City, State, ZIP/Postal code)</li>
          </ul>

          <h3 className="text-xl font-medium text-[rgb(108,76,241)]">Usage Data</h3>
          <p>Collected automatically, including:</p>
          <ul className="list-disc ml-6 space-y-2">
            <li>IP address</li>
            <li>Browser type/version</li>
            <li>Pages visited</li>
            <li>Time spent</li>
            <li>Device information</li>
            <li>Mobile identifiers</li>
          </ul>

          <h3 className="text-xl font-medium text-[rgb(108,76,241)]">Information Collected via Application</h3>
          <p>With your prior permission, the Application may collect:</p>
          <ul className="list-disc ml-6 space-y-2">
            <li>Photos or camera access</li>
            <li>Mic access</li>
          </ul>
          <p>This data may be stored on your device or on our servers, depending on the feature used.</p>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">3. Tracking Technologies and Cookies</h2>
          <p>We use cookies and similar technologies (e.g., web beacons, tags, scripts) to analyze, enhance, and improve user experience. You may control your cookie settings in your browser.</p>
          <ul className="list-disc ml-6 space-y-2">
            <li><strong>Cookies or Browser Cookies. </strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
            <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
          </ul>
          <p>Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">4. Use of Your Personal Data</h2>
          <ul className="list-disc ml-6 space-y-2">
            <li>Provide, maintain, and improve the Service</li>
            <li>Manage your account and user access</li>
            <li>Process orders or contracts</li>
            <li>Contact you (email, SMS, push notifications)</li>
            <li>Send promotional content (opt-out available)</li>
            <li>Handle support and user requests</li>
            <li>Analyze data and trends</li>
            <li>Facilitate business transfers</li>
          </ul>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">5. Sharing Your Personal Data</h2>
          <ul className="list-disc ml-6 space-y-2">
            <li><strong>Service Providers</strong> for technical and analytical purposes</li>
            <li><strong>Affiliates</strong> under this Privacy Policy</li>
            <li><strong>Business Partners</strong> for promotions or offers</li>
            <li><strong>Other Users</strong> (public interactions)</li>
            <li><strong>In Business Transfers</strong> such as mergers or acquisitions</li>
            <li><strong>With Your Consent</strong>, for any other purpose</li>
          </ul>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">6. Data Retention</h2>
          <p>We retain your data as long as necessary for legal, contractual, and operational purposes. Usage data is retained for analysis, unless longer retention is required by law.</p>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">7. International Data Transfers</h2>
          <p>Your data may be transferred and stored on servers outside your country. We ensure adequate data protection standards are met before any such transfer.</p>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">8. Deleting Your Personal Data</h2>
          <p>You can delete data via your account settings or contact us at:</p>
         <p className="text-[rgb(108,76,241)]">
   <a
    href="mailto:support@tendingtoinfinityacademy.com"
    className="text-[rgb(108,76,241)] underline"
  >
    support@tendingtoinfinityacademy.com
  </a>.
</p>

          <p>We may retain some data to comply with legal obligations.</p>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">9. Legal Disclosure</h2>
          <ul className="list-disc ml-6 space-y-2">
            <li>To comply with legal obligations</li>
            <li>To protect Company rights or safety</li>
            <li>To investigate misuse or unlawful activity</li>
            <li>Under court order or lawful request</li>
          </ul>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">10. Data Security</h2>
          <p>While we use reasonable security measures, no transmission over the internet is fully secure. We strive to protect your data but cannot guarantee its absolute security.</p>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">11. Children’s Privacy</h2>
          <p>Our Service is not intended for children under 13. We do not knowingly collect data from children. If we learn we’ve collected such data, we will delete it.</p>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">12. Third-Party Links</h2>
          <p>We may link to other websites. We are not responsible for the privacy practices or content of third-party sites. Please review their privacy policies.</p>

          <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">13. Changes to This Privacy Policy</h2>
          <p>We may update this Policy. You will be notified via email or a notice on our Website. Continued use of the Service after changes are posted implies acceptance.</p>

         <h2 className="text-2xl text-[rgb(108,76,241)] font-semibold">14. Contact Us</h2>
<p>
  If you have any questions, concerns, or requests regarding this Privacy Policy, please contact us at:
</p>
<p>
  Email:{" "}
  <a
    href="mailto:support@tendingtoinfinityacademy.com"
    className="text-[rgb(108,76,241)] underline"
  >
    support@tendingtoinfinityacademy.com
  </a>.
</p>

        </section>
      </div>

      <Footer />
    </div>
  );
};

export default PrivacyPolicyPage;
